name: Deploy Backend on distribution

on:
  push:
    branches: [ "distribution" ]  # distribution 브랜치에 푸시될 때 실행

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # 배포 단계 추가
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5  # SSH를 통해 서버에 연결
      with:
        host: ${{ secrets.HOST }}       # 서버의 IP 주소
        username: ${{ secrets.USERNAME }}  # SSH 유저 이름
        key: ${{ secrets.SSH_KEY }}     # SSH 키
        script: |
          cd /path/to/backend/project   # 백엔드 프로젝트가 위치한 디렉토리로 이동
          git pull origin distribution  # distribution 브랜치에서 최신 코드 가져오기
          ./gradlew build               # 백엔드 애플리케이션 빌드
          sudo systemctl restart backend-service  # 백엔드 서비스 재시작 (systemd로 관리되는 경우)

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
